//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::common::encrypto::types::KeyType;

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    Default,
)]
#[sea_orm(table_name = "t_key")]
pub struct Model {
    #[sea_orm(column_name = "_id", primary_key)]
    #[serde(skip)]
    pub id: i64,
    #[sea_orm(unique)]
    pub key_id: String,
    pub kms_id: String,
    pub key_type: KeyType,
    pub key_pair: Option<Json>,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct SymmtricKeyPair {
    pub key_pair: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct AsymmtricKeyPair {
    pub private_key: String,
    pub public_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
