//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use std::fmt::Debug;

use chrono::Utc;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::crypto::types::KeyType;

#[derive(
    Clone, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(table_name = "t_key")]
pub struct Model {
    #[sea_orm(column_name = "_id", primary_key)]
    #[serde(skip)]
    pub id: i64,
    #[sea_orm(unique)]
    pub key_id: String,
    pub kms_id: String,
    pub key_type: KeyType,
    pub pri_key: Option<String>,
    pub pub_key: Option<String>,
    pub version: String,
    #[serde(skip)]
    #[sea_orm(updated_at, default_current_timestamp)]
    pub updated_at: DateTime,
    #[serde(skip_deserializing)]
    #[sea_orm(created_at, default_current_timestamp)]
    pub created_at: DateTime,
}

impl Debug for Model {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Model")
            .field("id", &self.id)
            .field("key_id", &self.key_id)
            .field("kms_id", &self.kms_id)
            .field("key_type", &self.key_type)
            .field("version", &self.version)
            .field("updated_at", &self.updated_at)
            .field("created_at", &self.created_at)
            .finish()
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct SymmtricKeyPair {
    pub key_pair: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct AsymmtricKeyPair {
    pub private_key: String,
    pub public_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl Default for Model {
    fn default() -> Self {
        Self {
            id: Default::default(),
            key_id: Default::default(),
            kms_id: Default::default(),
            key_type: Default::default(),
            pri_key: Default::default(),
            pub_key: Default::default(),
            version: Default::default(),
            updated_at: Utc::now().naive_local(),
            created_at: Utc::now().naive_local(),
        }
    }
}
